sudo: required
services:
        - docker

before_install:
        - docker build -t alvinpoon96/react-test -f ./client/Dockerfile.dev ./client
 
script:
        - docker run -e CI=true alvinpoon96/react-test npm test
 
after_success:
        - docker build -t alvinpoon96/multi-container-client ./client
        - docker build -t alvinpoon96/multi-container-nginx ./nginx 
        - docker build -t alvinpoon96/multi-container-server ./server
        - docker build -t alvinpoon96/multi-container-worker ./worker      
