version: '3'
services:
  nginx:
    depends_on:
      - api
      - client
    restart: always # since this is a webserver we want it to always restart. This is important if not no traffic can come in
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - '8080:80'
  postgres: 
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: 'redis:latest'
  api:
    depends_on:
      - postgres
    build:
      context: ./server
      dockerfile: Dockerfile.dev
      # Define where the folder to look for the Dockerfile.dev and building of this image
    volumes:
        - /app/node_modules  # ensure that the node modules in the directory does not get overwritten by any folder we have on our local machine
        - ./server:/app # map everything in ./server to /app of the container
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGHOST=postgres
      - PGUSER=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    environment:
      - WDS_SOCKET_PORT=0
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules # ensure that the node modules in the directory does not get overwritten by any folder we have on our local machine
      - ./client:/app
  worker:
    depends_on:
      - redis
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379